title: Best site to Code! 
author: Odraudego
email: kaad08@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Discover all the latest about our products, technology, and culture on our official blog.


# social links
twitter_username: padawandude
github_username:  odraudego

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
